namespace PleasureToBurn;

/// <summary>One line on the job board. Plain data; generated by ContractManager each visit.</summary>
public sealed class JobOffer
{
    public required Site Site { get; init; }
    public required bool IsPrecision { get; init; }
    public required int ContrabandCount { get; init; }
    public required int EstimatedPay { get; init; }
    /// <summary>Return within this many seconds of accepting for the deadline bonus.</summary>
    public required float BonusSeconds { get; init; }
    public required float DistanceMetres { get; init; }
    public required string ReportLine { get; init; }
}

/// <summary>Itemised settlement for one completed job. Shown on the invoice screen.</summary>
public sealed class Invoice
{
    public required string Address { get; init; }
    public required bool IsPrecision { get; init; }
    public required int ContrabandBurned { get; init; }
    public required int ContrabandTotal { get; init; }
    public required int RatePerItem { get; init; }
    public required int BasePay { get; init; }
    public required int CollateralCount { get; init; }
    public required int CollateralPenalty { get; init; }
    public required bool MadeDeadline { get; init; }
    public required int DeadlineBonus { get; init; }
    public required float ReputationMultiplier { get; init; }
    public required int Total { get; init; }
    /// <summary>1..3</summary>
    public required int Stars { get; init; }
    public required int ReputationDelta { get; init; }
    public required float SecondsTaken { get; init; }
}
